Added popup for smaller screens
Ramzi-Abidi/Pong pull request #57
Opened 2024-02-02 16:20 UTC by ujjwxl

Added popup to inform that game is for PC users for the present

![Screenshot (1789)](https://github.com/Ramzi-Abidi/Pong/assets/128631648/2bfb3285-4ce6-4692-b7d5-5e8c0bdaaf82)

2024-02-02 16:42 UTC, Ramzi-Abidi commented
@ujjwxl appreciate your time, I think popup is not the best approach here 😅

It kind of ruined the UI, I think [react-alert](https://mui.com/material-ui/react-alert/) will be a better option !

Try using "**warning**" alert from top of the page. 

**Example of alerts:**

![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/264d1528-aea7-4d27-90b4-329bfe3bd047)

Sorry for the inconvenience! 😅

2024-02-02 16:45 UTC, Ramzi-Abidi commented on src/views/Home.tsx
@ujjwxl, appreciate your time. I don't think the popup is the best approach here, 😅 it kind of ruined the UI. I believe using [react-alert](https://mui.com/material-ui/react-alert/) would be a much better option!

Consider using the "warning" alert from the top of the page.

Sorry again for the inconvenience! 😅

2024-02-02 16:46 UTC, Ramzi-Abidi requested changes
@ujjwxl, appreciate your time. I don't think the popup is the best approach here, 😅 it kind of ruined the UI. I believe using [react-alert](https://mui.com/material-ui/react-alert/) would be a much better option!

Consider using the "warning" alert from the top of the page.

Sorry again for the inconvenience! 😅

2024-02-03 11:07 UTC, ujjwxl commented
Alright, will be working on these.

2024-03-12 09:26 UTC, closed without merging