Issue 40 fix
Ramzi-Abidi/Pong pull request #73
Opened 2024-02-14 21:06 UTC by aditya4196

Behaviour implemented :-
When in game mode, If screen tab switched or browser minimized, the game will be paused and should enter p to resume the game.

2024-02-15 12:38 UTC, Ramzi-Abidi commented
@aditya4196 Please, try next time to follow branch naming conventions as shown in [contrib-guide](https://github.com/Ramzi-Abidi/Pong/blob/main/CONTRIBUTING.md)

2024-02-15 17:19 UTC, aditya4196 commented
ohh Sorry, I will follow the process for this Issue if you want.
You can reject the PR and i can create a new feature branch in my repo with my changes and then generate a new PR

2024-02-15 18:31 UTC, Ramzi-Abidi commented on src/views/MultiplePlayerMode.tsx
try to add some type safety to the functions

2024-02-15 18:33 UTC, Ramzi-Abidi requested changes
@aditya4196 Thanks for the PR but please do the following:

- Try to add some type safety to functions and their return types
- Use proper branch name convention

2024-02-17 19:29 UTC, aditya4196 commented
@Ramzi-Abidi Sure. I would try to do it by today evening or by tomorrow afternoon.

2024-02-18 19:15 UTC, aditya4196 commented
@Ramzi-Abidi Just today I was working on this PR, When you say type safety, Are you talking about solution I coded for the Issue 40 or the previous issues solutions. I have tried to define models for every new features I have added for the previous issues.

2024-02-18 23:49 UTC, Ramzi-Abidi commented
> @Ramzi-Abidi Just today I was working on this PR, When you say type safety, Are you talking about solution I coded for the Issue 40 or the previous issues solutions. I have tried to define models for every new features I have added for the previous issues.

@aditya4196 Previous is code is fine, just try in this commit to add return types to the function that you wrote (we are using typescript not javascript).

And thanks for your time! 🙂

2024-02-19 03:45 UTC, aditya4196 commented
Got it

2024-02-20 22:55 UTC, merged